### ISSUE TITLE
Unlayer Smart Merge Tags not working

### ISSUE THREAD

**Issue by CrmDev23** [XRM-OSS/Xrm-Html-Templating#30]
Hi @DigitalFlow 

First of all, thank you for this great solution!

With the introduction of unlayer smart merge tags (5 days ago), we are facing issues with the email editor. Smart tags are not handled correctly. Steps to reproduce the issue:

1. Insert a merge tag into your html template.
2. Switch focus to another content section in the editor.
3. Merge tag from step 1. is being partially removed. Only _${{Snippet(_ is visible in the editor.

According to the unlayer docs, it should be possible to just disable this new feature.
https://docs.unlayer.com/changelog

What do you think?

**Comment by catalinpotinte** [comment]
Hi @DigitalFlow, 

We are experiencing the same issue in our CRM Dynamics 365 Instance: Version 1710 (9.2.22101.170) online - 2022 release wave 1.

We have installed the latest solution versions:
-  Xrm.Oss.Xrm-Html-Templating 1.4.3
- Xrm.Oss.Xrm-Templating-Language 3.9.4

 Steps to reproduce are basically the same as the ones  written above by @CrmDev23 

![image](https://user-images.githubusercontent.com/117435625/199927537-3e47b1ca-e244-4978-8567-2f5a9d75bdd4.png)

Any support/hints on how to solve this  will be greatly appreciated.

Best Regards,
Catalin

**Comment by CustomerEngagementer** [comment]
Dear @DigitalFlow 

we experience the same issue as reported above, since the latest unlayer update.
Disabling the new feature hasn`t worked for us so far :(
Any ideas?

Thanks and best regards
Sascha

**Comment by DigitalFlow** [comment]
Hi @CrmDev23 / @catalinpotinte / @CustomerEngagementer:

Sorry for being so late to reply.

I'm working on a fix. I disabled the smartMergeTags feature in my local dev environment already, but they seem to analyze the values that the Snippets enter into the text areas and fail on subsequent processes.

I hope to have a fix ready in the upcoming days - again, sorry for the delay.

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @CrmDev23 / @catalinpotinte / @CustomerEngagementer,

This is a bug in the upstream unlayer editor. There are already quite a few tickets regarding this issue in their [bug tracker](https://unlayer.canny.io/bug-reports).

I have just published a workaround as prerelease, can you test in your dev environment?
https://github.com/XRM-OSS/Xrm-Html-Templating/releases/tag/v1.4.5

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @CrmDev23 / @catalinpotinte / @CustomerEngagementer,

we found some additional issues, please try out [v1.4.6](https://github.com/XRM-OSS/Xrm-Html-Templating/releases/tag/v1.4.6), feedback would be appreciated :)

Kind regards,
Florian

**Comment by CustomerEngagementer** [comment]
Dear Florian

I tried to install the solution, however following error occurred:

Fehler beim Importieren der Lösung "Xrm.Oss.Xrm-Html-Templating": Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: WebResource, ObjectName: oss_/XrmHtmlTemplating/js/WebApiClient.js, Id: babdfec1-30da-e811-80ee-0050568e4745, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: RibbonCommand, ObjectName: oss_htmltemplate:oss.htmltemplate.SaveAs.Command, Id: d8836d28-786a-ed11-81ac-002248617d13, ParentObjectName: Menübandbefehl, ParentId: 00000000-0000-0000-0000-000000000000 .

Best regards
Sascha


​
Sascha Flathmann | Product Owner Customer Engagement Hub | ​Wincasa AG | +41 44 403 28 39 | ​www.wincasa.ch

**Comment by DigitalFlow** [comment]
Hi @CustomerEngagementer,

please try out [v1.4.7](https://github.com/XRM-OSS/Xrm-Html-Templating/releases/tag/v1.4.7), I was too eager to clean up the webresource dependencies in v.1.4.6, v.1.4.7 has the resource that was missing again.

Kind regards,
Florian

**Comment by CustomerEngagementer** [comment]
Hi Florian

With 1.4.7. import worked and initial tests look promising.
When I add a snippet it still gets resolved to its name, but when I save and reopen, the snippet with the $... is displayed correctly.

I will continue to monitor the behavior.

Thanks a lot!

Best regards,
Sascha



​
Sascha Flathmann | Product Owner Customer Engagement Hub | ​Wincasa AG | +41 44 403 28 39 | ​www.wincasa.ch
